<a href="https://colab.research.google.com/github/KedarDebadwar/python_series/blob/main/Numpy_lec_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array(range(16))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.shape #(c,)

(16,)

In [ ]:
a.ndim

1

In [ ]:
#reshape() #2D --> (r,c). #3D --> (d,r,c)

In [ ]:
a.reshape(8,2) #16=8*2. #11 (11*1), (1*11)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(4,5)

ValueError: cannot reshape array of size 16 into shape (4,5)

In [ ]:
a.reshape(5,4)

ValueError: cannot reshape array of size 16 into shape (5,4)

In [ ]:
a.reshape(8,-1) # 16/8=2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [ ]:
a = a.reshape(8,2)

In [ ]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
len(a)

8

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
#Transpose

a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a.T.shape

(4, 3)

In [ ]:
#Indexing

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1][2]

6

In [ ]:
a[1,2] #Recommended

6

In [ ]:
m1 = np.arange(1,10).reshape(3,3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m1[1,1]

5

In [ ]:
m1 = np.array([100,200,300,400,500,600])
m1[2,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
m1[[2,3]]

array([300, 400])

In [ ]:
m1 = np.arange(9).reshape(3,3)

In [ ]:
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
m1[[0,1,2],[0,1,2]] # => (0,0), (1,1), (2,2)

array([0, 4, 8])

In [ ]:
#Slicing

In [ ]:
m1 = np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
m1[:,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

#Quiz 1
a = [1,2,3,4,5] <br>
b = [8,7,6]<br>
a[3:] = b[::-2]<br>
print(a)

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]

In [ ]:
b[::-2]

[6, 8]

In [ ]:
a[3:]

[4, 5]

In [ ]:
a[3:] = b[::-2]

In [ ]:
a

[1, 2, 3, 6, 8]

In [ ]:
#Fancy indexing (masking)

In [ ]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
mask = m1<6
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
m1[mask]

array([0, 1, 2, 3, 4, 5])

In [ ]:
m1[m1<6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Quiz 2

a = np.array([0,1,2,3,4,5]) <br>
mask = (a%2 == 0) <br>
a[mask] = -1

In [ ]:
10%2

0

In [ ]:
10/2

5.0

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
#Aggregate func

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sum(a)

55

In [ ]:
np.mean(a)

5.5

In [ ]:
np.median(a)

5.5

In [ ]:
np.min(a) #a.min

1

In [ ]:
np.max(a) #a.max

10

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

In [ ]:
np.sum(a, axis=0) #vertical

array([12, 15, 18, 21])

In [ ]:
np.sum(a,axis = 1) #horizontal

array([ 6, 22, 38])

In [ ]:
#logical operations

In [ ]:
prices = np.array([50, 45, 25, 20, 35])
budget = 30
can_afford = np.any(prices<=budget)
if can_afford:
    print("Yes, atleast 1 item")
else:
    print("No, not even 1 item")

Yes, atleast 1 item


In [ ]:
chores = np.array([1, 1, 1, 1, 0]) #status as 0/1

In [ ]:
all_chores_done = np.all(chores == 1)

if all_chores_done:
    print("Yes, all chores done")
else:
    print("No, not all chores done")

No, not all chores done


In [ ]:
#Multiple conditions
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr[arr>0] = 1
arr[arr<0]= -1
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [ ]:
#np.where()
prices = np.array([45, 55, 60, 75, 40, 90])
discounted_prices = np.where(prices > 50, prices * 0.9, prices) #(cond, x, y)
print(prices)
print(discounted_prices)


[45 55 60 75 40 90]
[45.  49.5 54.  67.5 40.  81. ]


In [ ]:
#Quiz 3
a = np.array([0,2,3])
b = np.array([1,3,5])
a>=b

array([False, False, False])

In [ ]:
arr1 = np.array([2,1,0,3])
print(np.where(arr1))

(array([0, 1, 3]),)


In [ ]:
#Quiz :

arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0])
print(np.where(arr))

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
#Use case

In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 10.3MB/s]


In [ ]:
data = np.loadtxt('/content/fit.txt', dtype='str')

In [ ]:
data.shape

(96, 6)

In [ ]:
data.ndim

2

In [ ]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [ ]:
data[1]

array(['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'], dtype='<U10')

In [ ]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [ ]:
data[:, 0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
data_t = data.T

In [ ]:
data_t

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
data_t[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
data_t.shape

(6, 96)

In [ ]:
date, step_count, mood, calories_burned, hours_of_sleep, activity_status = data.T

step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [ ]:
step_count.dtype

dtype('<U10')

In [ ]:
step_count = np.array(step_count,dtype='int')
step_count.dtype

dtype('int64')

In [ ]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
step_count.shape

(96,)

In [ ]:
calories_burned = np.array(calories_burned, dtype = 'int')
calories_burned.dtype

dtype('int64')

In [ ]:
hours_of_sleep = np.array(hours_of_sleep, dtype = 'int')
hours_of_sleep.dtype

dtype('int64')

In [ ]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [ ]:
step_count_happy = step_count[mood == 'Happy']
len(step_count_happy)

40

In [ ]:
step_count_sad = step_count[mood == 'Sad']

len(step_count_sad)

29

In [ ]:
step_count_neutral = step_count[mood == 'Neutral']

len(step_count_neutral)

27

In [ ]:
step_count_happy_or_neutral = step_count[(mood == 'Neutral') | (mood == 'Happy')]

len(step_count_happy_or_neutral)

67

In [ ]:
np.mean(step_count_sad)

2103.0689655172414

In [ ]:
np.mean(step_count_happy)


3392.725

In [ ]:
np.mean(step_count_neutral)

3153.777777777778

In [ ]:
#mood when the step count > 4000
np.unique(mood[step_count > 4000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [ ]:

np.unique(mood[step_count <= 2000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))